services:
  smtp2sms:
    build:
      context: .
      dockerfile: Dockerfile
    image: smtp2sms:payamak
    container_name: smtp2sms
    restart: always
    ports:
      - "${HOST_SMTP_PORT:-25}:25"
    volumes:
      - ./.env:/app/.env
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - .env
